// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef myWindow_h
#define myWindow_h
#include <FL/Fl.H>
#include "myWinApp.h"
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *pMain_win;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *pMain_menu;
extern MyGlWindow *pRender_glWin;
#include <FL/Fl_Button.H>
extern void GenCluster(Fl_Button*, void*);
extern Fl_Button *pSaveClt_bttn;
#include <FL/Fl_Group.H>
extern Fl_Group *pTarget_group;
extern void DisplayTarget(Fl_Button*, void*);
extern Fl_Button *pDisTar_bttn;
#include <FL/Fl_Check_Button.H>
extern void SetTarget(Fl_Check_Button*, void*);
extern Fl_Check_Button *pSetTar_bttn;
extern void ClearTarget(Fl_Button*, void*);
extern Fl_Button *pClrTar_bttn;
extern Fl_Group *pSel_group;
extern void AddSelecter(Fl_Button*, void*);
extern Fl_Button *pAddSel_bttn;
extern void EditSelecter(Fl_Check_Button*, void*);
extern Fl_Check_Button *pEdtSel_bttn;
extern Fl_Group *pColorFr_group;
#include <FL/Fl_Input.H>
extern Fl_Input *pRFr_input;
extern Fl_Input *pGFr_input;
extern Fl_Input *pBFr_input;
extern Fl_Input *pAFr_input;
extern Fl_Group *pColorTo_group;
extern Fl_Input *pRTo_input;
extern Fl_Input *pGTo_input;
extern Fl_Input *pBTo_input;
extern Fl_Input *pATo_input;
extern void CopyColor(Fl_Button*, void*);
extern Fl_Button *pCopyColor_bttn;
extern Fl_Button *pDelSel_bttn;
extern void SetColor(Fl_Button*, void*);
extern Fl_Button *pSetC_bttn;
extern void Truncate(Fl_Button*, void*);
extern Fl_Button *pTruncate_bttn;
#include <FL/Fl_Value_Slider.H>
extern void ReduceLevel(Fl_Value_Slider*, void*);
extern Fl_Value_Slider *pLevelReduce_valScl;
extern void ReduceLevel(Fl_Button*, void*);
extern Fl_Button *pShowRed_bttn;
Fl_Double_Window* make_window();
#endif
